const dashboard = {
  monthSelector: {
    prevMonth: "Mois précédent",
    nextMonth: "Mois suivant",
    chooseMonth: (month: string) => (month ? `Choisir le mois, actuellement ${month}` : "Choisir le mois"),
    prevYear: "Année précédente",
    nextYear: "Année suivante",
    goToMonth: (month: string) => `Aller à ${month}`,
  },
  budgetHero: {
    remainingLabel: (month: string) => `${month} — budget restant`,
    editBudgetAria: "Modifier le budget alloué",
    editAmountTitle: "Modifier le montant initial",
    overBudget: "↓ au-dessus du budget",
    withinBudget: "↑ dans le budget",
    atCurrentPace: "au rythme actuel",
    setBudgetPrompt: "Définir le budget du mois",
    donutAria: "Répartition du budget consommé",
    fixed: "Fixes",
    variables: "Variables",
    available: "Restant",
  },
  categoryBreakdown: {
    title: "Répartition par catégorie",
    meta: (month: string) => `${month} · part des variables`,
    barAria: "Répartition mensuelle par catégorie",
    uncategorized: "sans catégorie",
    trendStable: "stable",
    empty: "Aucune dépense ce mois.",
  },
  dailySparkline: {
    title: "Consommation jour par jour",
    average: "Moyenne",
    peak: "Pic",
    avgShort: "moy.",
    chartAria: "Consommation quotidienne",
    // Caption naming the historical basis of the projected (dashed) tail (COS-27).
    projectionBasis: {
      sameMonthLastYear: "Projection basée sur le même mois l'an dernier",
      sameMonthTwoYearsAgo: "Projection basée sur le même mois il y a deux ans",
      previousMonth: "Projection basée sur le mois précédent",
    },
  },
  fixedExpenses: {
    title: "Dépenses fixes",
    linesSchedule: (count: number, month: string) => `${count} lignes · échéancier ${month}`,
    addAria: "Ajouter une dépense fixe",
    monthly: "Mensuel",
    annualized: "Annualisé",
    upcomingBy: (date: string) => `À venir d'ici le ${date}`,
    deleteConfirm: "Supprimer ?",
    cancel: "Annuler",
    confirm: "Confirmer",
    invoiceTitle: "Facture",
    editTitle: "Modifier",
    deleteTitle: "Supprimer",
    empty: "Aucune dépense fixe ce mois.",
  },
  forecastStrip: {
    spent: (date: string) => `Dépensé · ${date}`,
    pctOfBudget: (pct: number) => `${pct}% du budget`,
    todayMarker: "aujourd'hui",
    realized: "réalisé",
    projection: "projection",
    endOfMonthProjection: "Projection fin de mois",
    above: "au-dessus",
    underBudget: "sous budget",
  },
  insightsRibbon: {
    paceLabel: "Sur le rythme",
    risingLabel: "Catégorie en hausse",
    risingEmpty: "Aucune catégorie ce mois.",
    remainingLabel: "Reste à vivre",
  },
  weeklyCeiling: {
    title: "Plafond hebdomadaire",
    editTitle: "Modifier le plafond",
    upcoming: "à venir",
    empty: "Pas encore de données.",
    avgLabel: "Moyenne hebdo",
    pctOfCeiling: (pct: number) => `${pct}% du plafond`,
    ceilingAmount: (amount: string) => `Plafond ${amount} €`,
    withinBudget: "dans le budget",
    overrun: "dépassement",
  },
};

export default dashboard;
