const dashboard = {
  monthSelector: {
    prevMonth: "Mois précédent",
    nextMonth: "Mois suivant",
    chooseMonth: (month: string) => (month ? `Choisir le mois, actuellement ${month}` : "Choisir le mois"),
    prevYear: "Année précédente",
    nextYear: "Année suivante",
    goToMonth: (month: string) => `Aller à ${month}`,
  },
  budgetHero: {
    remainingLabel: (month: string) => `${month} — budget restant`,
    editBudgetAria: "Modifier le budget alloué",
    editAmountTitle: "Modifier le montant initial",
    allocated: "sur {amount} alloués",
    overBudget: "↓ au-dessus du budget",
    withinBudget: "↑ dans le budget",
    atCurrentPace: "au rythme actuel",
    setBudgetPrompt: "Définir le budget du mois",
    donutAria: "Répartition du budget consommé",
    donutUsed: "utilisé",
    fixed: "Fixes",
    variables: "Variables",
    available: "Restant",
  },
  categoryBreakdown: {
    title: "Répartition par catégorie",
    meta: (month: string) => `${month} · part des variables`,
    barAria: "Répartition mensuelle par catégorie",
    uncategorized: "sans catégorie",
    trendStable: "stable",
    trendNew: "nouv.",
    empty: "Aucune dépense ce mois.",
  },
  dailySparkline: {
    title: "Consommation jour par jour",
    averageLine: "Moyenne {avg}/jour",
    peak: "Pic",
    avgShort: "moy.",
    chartAria: "Consommation quotidienne",
    // Caption naming the historical basis of the projected (dashed) tail (COS-27).
    projectionBasis: {
      sameMonthLastYear: "Projection basée sur le même mois l'an dernier",
      sameMonthTwoYearsAgo: "Projection basée sur le même mois il y a deux ans",
      previousMonth: "Projection basée sur le mois précédent",
    },
  },
  fixedExpenses: {
    title: "Dépenses fixes",
    linesSchedule: (count: number, month: string) => `${count} lignes · échéancier ${month}`,
    addAria: "Ajouter une dépense fixe",
    monthly: "Mensuel",
    annualized: "Annualisé",
    upcomingBy: (date: string) => `À venir d'ici le ${date}`,
    debitsLine: (count: number) => `{count} prélèvement${count > 1 ? "s" : ""} · {sum}`,
    deleteConfirm: "Supprimer ?",
    cancel: "Annuler",
    confirm: "Confirmer",
    invoiceTitle: "Facture",
    editTitle: "Modifier",
    deleteTitle: "Supprimer",
    empty: "Aucune dépense fixe ce mois.",
  },
  forecastStrip: {
    spent: (date: string) => `Dépensé · ${date}`,
    budgetLabel: " € budget",
    pctOfBudget: (pct: number) => `${pct}% du budget`,
    todayMarker: "aujourd'hui",
    realized: "réalisé",
    projection: "projection",
    endOfMonthProjection: "Projection fin de mois",
    above: "au-dessus",
    underBudget: "sous budget",
  },
  // Sentences with data interleaved are {token} templates rendered through
  // interpolate() (@i18n/interpolate): one key per sentence, word order free
  // per language, styled values injected by the component. Plural-dependent
  // sentences are functions selecting the right template variant.
  insightsRibbon: {
    paceLabel: "Sur le rythme",
    paceEmpty: "En attente de plus de données pour comparer le rythme. ",
    paceSentence: "Consommation {pace} que la moyenne 3 mois. ",
    paceSame: "au même rythme",
    paceFaster: (pct: number) => `~${pct}% plus vite`,
    paceSlower: (pct: number) => `~${pct}% moins vite`,
    budgetOutcomeInProgress: "À ce rythme, le mois se termine {state}.",
    budgetOutcomeLastDay: "Le mois se termine aujourd'hui, {state}.",
    budgetOutcomePast: "Le mois s'est terminé {state}.",
    underBudget: "sous le budget",
    overBudget: "au-dessus du budget",
    risingLabel: "Catégorie en hausse",
    risingEmpty: "Aucune hausse ce mois.",
    risingSentence: "{category} à {delta} vs le mois dernier.",
    remainingLabel: "Reste à vivre",
    remainingSentence: "Il reste {perDay}/jour à dépenser d'ici le {date} pour rester dans le budget.",
    overspentSentence: "Budget dépassé de {amount} sur le mois.",
    unspentSentence: "{amount} de budget non dépensé sur le mois.",
    busiestLabel: "Semaine la plus active",
    busiestEmpty: "Aucune transaction ce mois.",
    transactions: (count: number) => `${count} transaction${count > 1 ? "s" : ""}`,
    busiestRange: (from: string, to: string) => `${from} au ${to}`,
    busiestSentence: "{transactions} du {range}.",
  },
  weeklyCeiling: {
    title: "Plafond hebdomadaire",
    editTitle: "Modifier le plafond",
    upcoming: "à venir",
    empty: "Pas encore de données.",
    avgLabel: "Moyenne hebdo",
    pctOfCeiling: (pct: number) => `${pct}% du plafond`,
    ceilingAmount: (amount: string) => `Plafond ${amount} €`,
    withinBudget: "dans le budget",
    overrun: "dépassement",
  },
};

export default dashboard;
