import type frDashboard from "@text/fr/dashboard";

const dashboard: typeof frDashboard = {
  monthSelector: {
    prevMonth: "Previous month",
    nextMonth: "Next month",
    chooseMonth: (month: string) => (month ? `Choose month, currently ${month}` : "Choose month"),
    prevYear: "Previous year",
    nextYear: "Next year",
    goToMonth: (month: string) => `Go to ${month}`,
  },
  budgetHero: {
    remainingLabel: (month: string) => `${month} — remaining budget`,
    editBudgetAria: "Edit allocated budget",
    editAmountTitle: "Edit initial amount",
    allocated: "of {amount} allocated",
    overBudget: "↓ over budget",
    withinBudget: "↑ within budget",
    atCurrentPace: "at the current pace",
    setBudgetPrompt: "Set this month's budget",
    donutAria: "Breakdown of spent budget",
    donutUsed: "used",
    fixed: "Fixed",
    variables: "Variable",
    available: "Remaining",
  },
  categoryBreakdown: {
    title: "Breakdown by category",
    meta: (month: string) => `${month} · share of variables`,
    barAria: "Monthly breakdown by category",
    uncategorized: "uncategorized",
    trendStable: "stable",
    trendNew: "new",
    empty: "No spendings this month.",
  },
  dailySparkline: {
    title: "Day-by-day spending",
    averageLine: "Average {avg}/day",
    peak: "Peak",
    avgShort: "avg.",
    chartAria: "Daily spending",
    // Caption naming the historical basis of the projected (dashed) tail (COS-27).
    projectionBasis: {
      sameMonthLastYear: "Projection based on the same month last year",
      sameMonthTwoYearsAgo: "Projection based on the same month two years ago",
      previousMonth: "Projection based on the previous month",
    },
  },
  fixedExpenses: {
    title: "Fixed expenses",
    linesSchedule: (count: number, month: string) => `${count} ${count === 1 ? "line" : "lines"} · ${month} schedule`,
    addAria: "Add a fixed expense",
    monthly: "Monthly",
    annualized: "Annualized",
    upcomingBy: (date: string) => `Upcoming by ${date}`,
    debitsLine: (count: number) => `{count} debit${count === 1 ? "" : "s"} · {sum}`,
    deleteConfirm: "Delete?",
    cancel: "Cancel",
    confirm: "Confirm",
    invoiceTitle: "Invoice",
    editTitle: "Edit",
    deleteTitle: "Delete",
    empty: "No fixed expenses this month.",
  },
  forecastStrip: {
    spent: (date: string) => `Spent · ${date}`,
    budgetLabel: " € budget",
    pctOfBudget: (pct: number) => `${pct}% of budget`,
    todayMarker: "today",
    realized: "actual",
    projection: "projection",
    endOfMonthProjection: "End-of-month projection",
    above: "over",
    underBudget: "under budget",
  },
  insightsRibbon: {
    paceLabel: "On pace",
    paceEmpty: "Waiting for more data to compare pace. ",
    paceSentence: "Spending {pace} than the 3-month average. ",
    paceSame: "at the same pace",
    paceFaster: (pct: number) => `~${pct}% faster`,
    paceSlower: (pct: number) => `~${pct}% slower`,
    budgetOutcomeInProgress: "At this pace, the month ends {state}.",
    budgetOutcomeLastDay: "The month ends today, {state}.",
    budgetOutcomePast: "The month ended {state}.",
    underBudget: "under budget",
    overBudget: "over budget",
    risingLabel: "Rising category",
    risingEmpty: "No increase this month.",
    risingSentence: "{category} at {delta} vs last month.",
    remainingLabel: "Left to spend",
    remainingSentence: "{perDay}/day left to spend until {date} to stay on budget.",
    overspentSentence: "{amount} over budget this month.",
    unspentSentence: "{amount} of budget left unspent this month.",
    busiestLabel: "Busiest week",
    busiestEmpty: "No transactions this month.",
    transactions: (count: number) => `${count} transaction${count === 1 ? "" : "s"}`,
    busiestRange: (from: string, to: string) => `${from} to ${to}`,
    busiestSentence: "{transactions} from {range}.",
  },
  weeklyCeiling: {
    title: "Weekly ceiling",
    editTitle: "Edit ceiling",
    upcoming: "upcoming",
    empty: "No data yet.",
    avgLabel: "Weekly average",
    pctOfCeiling: (pct: number) => `${pct}% of ceiling`,
    ceilingAmount: (amount: string) => `Ceiling ${amount} €`,
    withinBudget: "within budget",
    overrun: "overrun",
  },
};

export default dashboard;
