import type frSpendings from "@text/fr/spendings";

const spendings: typeof frSpendings = {
  noCategory: "uncategorized",
  actions: {
    cancel: "Cancel",
    confirm: "Confirm",
  },
  dashboard: {
    weeklyStats: {
      headerTitle: "totals by period",
      weeklyCeiling: "weekly ceiling",
      weeklySpendings: "average weekly spendings",
    },
    monthlyBudget: {
      initialAmount: "Initial amount",
      remaining: "Remaining",
      total: "Month total",
      percentLabel: "spent",
    },
    monthlyCharts: {
      headerTitle: "monthly breakdown",
    },
    weeklyCharts: {
      headerTitle: "weekly breakdown",
    },
    recurrings: {
      show: "Show recurring",
      hide: "Hide recurring",
    },
  },
  dayItem: {
    remainingBudget: "Maximum daily budget",
  },
  dayCard: {
    noResults: "No results",
    total: "TOTAL",
    addSpending: "Add a spending on this day",
  },
  list: {
    empty: "No spendings",
  },
  sortItem: {
    label: "Label",
    category: "Categories",
    amount: "Amount",
  },
  filter: {
    label: "Filter",
    all: "All",
    // Caret at the end of the one-line category strip; opens the full list overlay.
    showAllAria: "Show all categories",
  },
  toolbar: {
    // Week-scoped client-side filter — distinct from the whole-history search
    // (COS-118), which lives next to it and opens the search modal.
    searchPlaceholder: "Filter the week…",
  },
  view: {
    newSpending: "New spending",
  },
  breakdown: {
    title: "Breakdown by category",
    expandAria: "Show category breakdown",
    collapseAria: "Hide category breakdown",
    expandHint: "Expand to see details",
    // Label of the stacked bar as a whole — the per-category detail is read from
    // the list below it.
    barAria: "Weekly breakdown by category",
    // Suffix appended after the week range label in the pane header.
    rangeSuffix: " · week",
    // Per-category trend badge vs the previous week (COS-35).
    trendStable: "stable",
    trendNew: "new",
  },
  summary: {
    remaining: "Remaining budget",
    weekTotal: "Week total",
    transactions: "Transactions",
    transactionsSub: (perDay: string) => `over 7 days · ${perDay}/day`,
    avgPerDay: "Average / day",
    biggest: "Largest",
    overCeiling: (amount: number) => `+${amount} € vs ceiling`,
    underCeiling: (amount: number) => `−${amount} € under ceiling`,
    ceilingUndefined: "ceiling not set",
    deltaStable: "stable vs last week",
    deltaUp: (amount: number) => `+${amount} € vs last week`,
    deltaDown: (amount: number) => `−${amount} € vs last week`,
  },
  modal: {
    title: {
      edit: (recurring: boolean) => (recurring ? "Edit fixed expense" : "Edit spending"),
      create: (recurring: boolean) => (recurring ? "New fixed expense" : "New spending"),
    },
    submit: {
      save: "Save",
      add: "Add spending",
    },
    recurringToggle: "Monthly recurring",
    attachReceipt: "Attach a receipt",
    fileSize: {
      bytes: "B",
      kilobytes: "KB",
      megabytes: "MB",
    },
    copyPreviousMonth: "Copy fixed expenses from last month",
    fields: {
      amount: "Amount",
      category: "Category",
      date: "Date",
      label: "Label",
      labelPlaceholder: "e.g. Local bakery",
    },
    category: {
      triggerEmpty: "None",
      searchPlaceholder: "Search or type…",
      commandEmpty: "No categories.",
      clearOption: "No category",
      frequent: "Frequent",
    },
    date: {
      prevDayAria: "Previous day",
      nextDayAria: "Next day",
    },
    receipt: {
      dropPrompt: "Drop a receipt or",
      browse: "browse",
      fileTypes: "jpg, png, webp",
      removeAria: "Remove receipt",
    },
    validation: {
      labelRequired: "Label required",
      amountRequired: "Amount required",
    },
  },
  item: {
    deleteConfirm: "Delete this spending?",
    actions: {
      edit: "Edit",
      delete: "Delete",
    },
  },
  txRow: {
    deleteAria: "Confirm deletion",
    confirmAria: "Confirm the action",
    receiptAttachedAria: "receipt attached",
    viewReceipt: "View receipt",
    addReceipt: "Add a receipt",
  },
  invoiceModal: {
    noInvoice: "No receipt",
    fileTooBig: "The file is too large",
    chooseFile: "Choose a file",
    fileTypeWarning: "(jpg, png, webp, gif)",
    invalidFileType: "The file is not a valid image",
    send: "Send",
    delete: "Delete receipt",
    enlargeAria: "Enlarge receipt",
    imageAlt: "receipt",
    previewAlt: "receipt preview",
    deleteConfirmTitle: "Delete receipt?",
    lightboxTitle: "Receipt — preview",
  },
  spendingsListModal: {
    total: "total",
    projection: "end-of-month projection",
    filter: "filter",
    searchPlaceholder: "Search…",
    noCategoryLabel: "uncategorized",
    dayTotal: "Day total",
    cumulativeTotal: "Cumulative total",
    weekWord: "for the week",
    monthWord: "for the month",
    seeWeek: "View the corresponding week",
    noSpendings: "No spendings for this category.",
    noMatch: "No matching spendings.",
    close: "Close",
    // Breakdown of the category by label pattern (PFA-168). "Other" is the
    // catch-all bucket: the labels that match no pattern, plus the folded tail.
    patterns: {
      title: "breakdown by pattern",
      other: "Other",
    },
  },
  groups: {
    modeAria: "Entry type",
    modeSingle: "Single spending",
    modeGroup: "Group · one receipt",
    editTitle: "Edit group",
    nameLabel: "Store / group name",
    namePlaceholder: "e.g. Corner supermarket",
    lines: "Lines",
    columnCategory: "Category",
    columnDetail: "Detail",
    columnDetailOptional: "(optional)",
    columnAmount: "Amount",
    detailPlaceholder: "e.g. groceries",
    detailAria: "Detail",
    amountPlaceholder: "12+3.5+7.5",
    amountHint: "Sums allowed: 12+3.5+7.5",
    amountAria: "Amount",
    addLine: "Add a line",
    removeLine: "Remove the line",
    linesSummary: (lines: number, categories: number) =>
      `${lines} line${lines > 1 ? "s" : ""} · ${categories} categor${categories > 1 ? "ies" : "y"}`,
    total: "Total",
    attachReceipt: "Attach a receipt (whole group)",
    submitAdd: (lines: number) => `Add group · ${lines} line${lines > 1 ? "s" : ""}`,
    nameRequired: "Name required",
    expandAria: "Expand the group",
    collapseAria: "Collapse the group",
    ungroup: "Ungroup",
    deleteConfirm: (lines: number) => `Delete the group and its ${lines} lines?`,
    ungroupConfirm: (lines: number) => `Ungroup into ${lines} separate spendings?`,
    sharedReceiptTitle: (count: number) => `Receipt shared with ${count} spendings`,
    selection: {
      start: "Select spendings",
      selectRow: "Select",
      stop: "Finish selecting",
      selected: (_count: number) => "selected",
      atLeastTwo: "Select at least 2",
      sameDayOnly: "Grouping: same day only",
      group: "Group",
      sharedReceipt: "Shared receipt",
      exit: "Leave selection (Esc)",
    },
    merge: {
      title: (count: number) => `Group ${count} spendings`,
      name: "Group name",
      lines: "Group lines",
      keptReceiptBefore: "The receipt of",
      keptReceiptAfter: "will be kept and shared by the whole group.",
      receipt: "Receipt",
      receiptHint: "— optional, one for the whole group",
      submit: "Create group",
    },
    share: {
      title: "Shared receipt",
      lead: (count: number) => `One receipt, attached to these ${count} spendings. They stay separate in the list.`,
      count: (count: number) => `${count} spendings`,
      already: (count: number) =>
        count > 1 ? `${count} spendings already have a receipt` : "1 spending already has a receipt",
      alreadyAfter: " — it will be replaced by this one.",
      submit: (count: number) => `Attach to ${count} spendings`,
    },
    receipt: {
      sharedTitle: "Shared receipt",
      sharedTag: (count: number) => `${count} spendings`,
      groupTag: "Group",
      covers: (count: number) => `This receipt covers ${count} spendings`,
      ticketDetail: "Receipt details",
      linesCount: (lines: number) => `${lines} lines`,
      detach: "Detach from this receipt",
      deleteShared: (count: number) => `Delete the receipt of the ${count} spendings`,
      deleteGroup: "Delete the group's receipt",
    },
  },
  toasts: {
    spendingCreated: "Spending created",
    spendingUpdated: "Spending updated",
    spendingDeleted: "Spending deleted",
    recurringCreated: "Fixed expense created",
    recurringUpdated: "Fixed expense updated",
    recurringDeleted: "Fixed expense deleted",
    recurringsCopied: "Fixed expenses created",
    receiptUploadFailed: "Receipt not attached — retry from the spending row",
    groupCreated: "Group created",
    groupUpdated: "Group updated",
    groupDeleted: "Group deleted",
    ungrouped: "Group undone",
    grouped: "Spendings grouped",
    receiptShared: "Shared receipt attached",
    receiptDetached: "Receipt detached",
  },
};

export default spendings;
